- name: create ec2 instaces 
  amazon.aws.ec2_instance:
    aws_access_key: "{{access_key}}"
    aws_secret_key: "{{secret_key}}"
    instance_type: t3.small
    image_id: ami-123456
    count: 3
    region: us-east-2
    network:
      assign_public_ip: true
      security_group: default
    vpc_subnet_id: subnet-0123456
    state: present
    tags:
      foo: bar
